erDiagram
    "**core_members**" ||..|| "**nexus_customers**" : "is a"
    "**nexus_customers**" ||..o{ "**nexus_customer_addresses**" : ""
    "**nexus_customers**" ||..o{ "**nexus_customer_cards**" : ""
    "**nexus_customer_fields**" ||..o{ "**nexus_customers**" : "adds column"
    "**nexus_customers**" ||..o{ "**nexus_alternate_contacts**" : "main_id"
    "**nexus_customers**" ||..o{ "**nexus_alternate_contacts**" : "alt_id"
    "**nexus_customers**" ||..o{ "**nexus_notes**" : ""
    "**nexus_customers**" ||..o{ "**nexus_customer_spend**" : ""
    "**nexus_customers**" ||..o{ "**nexus_invoices**" : ""
    "**nexus_invoices**" ||..o{ "**nexus_transactions**" : ""
    "**nexus_customers**" ||..o{ "**nexus_transactions**" : ""
    "**nexus_transactions**" }o..o| "**nexus_paymethods**" : ""
    "**nexus_customers**" ||..o{ "**nexus_billing_agreements**" : ""
    "**nexus_billing_agreements**" }o..|| "**nexus_paymethods**" : ""
    "**nexus_customer_cards**" }o..|| "**nexus_paymethods**" : ""
    "**nexus_donate_goals**" ||..o{ "**nexus_donate_logs**" : ""
    "**nexus_customers**" ||..o{ "**nexus_donate_logs**" : ""
    "**nexus_invoices**" ||..o| "**nexus_donate_logs**" : ""
    "**nexus_customers**" ||..o{ "**nexus_payouts**" : ""
    "**nexus_transactions**" }o..o| "**nexus_fraud_rules**" : ""
    "**nexus_invoices**" ||..o{ "**nexus_invoice_tracker**" : ""
    "**nexus_customers**" ||..o{ "**nexus_invoice_tracker**" : ""
    "**nexus_coupons**" }o..o{ "**nexus_invoices**" : "redemption"
    "**nexus_referral_rules**" }o..o{ "**nexus_packages**" : "purchase rules"
    "**nexus_packages**" }o..|| "**nexus_package_groups**" : ""
    "**nexus_packages**" ||..o| "**nexus_packages_products**" : "subtype"
    "**nexus_packages**" ||..o| "**nexus_packages_ads**" : "subtype"
    "**nexus_packages**" ||..o{ "**nexus_package_images**" : ""
    "**nexus_packages**" ||..o| "**nexus_package_base_prices**" : ""
    "**nexus_packages**" ||..o{ "**nexus_product_options**" : ""
    "**nexus_packages**" ||..o{ "**nexus_reviews**" : ""
    "**nexus_packages**" }o..|| "**nexus_tax**" : ""
    "**nexus_package_filters**" ||..o{ "**nexus_package_filters_values**" : ""
    "**nexus_package_filters**" ||..o{ "**nexus_package_filters_map**" : ""
    "**nexus_packages**" ||..o{ "**nexus_package_filters_map**" : ""
    "**nexus_package_fields**" }o..o{ "**nexus_packages**" : ""
    "**nexus_packages_products**" }o..o{ "**nexus_shipping**" : ""
    "**nexus_ship_orders**" }o..|| "**nexus_shipping**" : ""
    "**nexus_ship_orders**" }o..|| "**nexus_invoices**" : ""
    "**nexus_packages**" ||..o| "**tapestry_packages**" : "p_id = id"
    "**nexus_packages**" ||..o{ "**nexus_purchases**" : ""
    "**nexus_purchases**" ||..o{ "**nexus_purchases**" : "ps_parent, self"
    "**nexus_purchases**" ||..o{ "**nexus_cart_uploads**" : ""
    "**nexus_customers**" ||..o{ "**nexus_purchases**" : ""
    "**nexus_invoices**" ||..o{ "**nexus_purchases**" : "ps_original_invoice"
    "**nexus_purchases**" }o..o| "**nexus_billing_agreements**" : ""
    "**nexus_purchases**" }o..o| "**nexus_tax**" : ""
    "**nexus_purchases**" ||..o{ "**nexus_licensekeys**" : ""
    "**nexus_customers**" ||..o{ "**nexus_licensekeys**" : ""
    "**nexus_customers**" ||..o{ "**nexus_member_subscriptions**" : ""
    "**nexus_member_subscription_packages**" ||..o{ "**nexus_member_subscriptions**" : ""
    "**nexus_purchases**" ||..o| "**nexus_member_subscriptions**" : ""
    "**nexus_invoices**" ||..o| "**nexus_member_subscriptions**" : ""
    "**nexus_tax**" ||..o{ "**nexus_member_subscription_packages**" : ""
    "**nexus_customers**" ||..o{ "**nexus_support_requests**" : ""
    "**nexus_purchases**" ||..o{ "**nexus_support_requests**" : ""
    "**nexus_support_departments**" ||..o{ "**nexus_support_requests**" : ""
    "**nexus_support_statuses**" ||..o{ "**nexus_support_requests**" : ""
    "**nexus_support_severities**" ||..o{ "**nexus_support_requests**" : ""
    "**nexus_support_requests**" ||..o{ "**nexus_support_replies**" : ""
    "**nexus_support_requests**" ||..o{ "**nexus_support_request_log**" : ""
    "**nexus_support_replies**" ||..o| "**nexus_support_ratings**" : ""
    "**nexus_support_requests**" ||..o{ "**nexus_support_tracker**" : ""
    "**nexus_support_requests**" ||..o{ "**nexus_support_views**" : ""
    "**nexus_support_departments**" ||..o{ "**nexus_support_fields**" : ""
    "**nexus_support_departments**" ||..o{ "**nexus_support_stock_actions**" : ""
    "**nexus_support_departments**" ||..o{ "**nexus_support_staff_dpt_order**" : ""
    "**nexus_support_departments**" ||..o{ "**nexus_support_notify**" : ""
    "**nexus_support_requests**" ||..o{ "**tapestry_support_request_schools**" : ""
    "**tapestry_schools**" ||..o{ "**tapestry_support_request_schools**" : ""
    "**core_members**" ||..o{ "**nexus_support_streams**" : "stream_owner"
    "**core_members**" ||..o{ "**nexus_support_staff_preferences**" : "staff_id"
    "**core_members**" ||..o{ "**nexus_support_staff_dpt_order**" : "staff_id"
    "**core_members**" ||..o{ "**nexus_support_notify**" : "staff_id"
    "**tapestry_schools**" ||..o| "**nexus_purchases**" : "school_pkg_id"
    "**tapestry_schools**" }o..|| "**nexus_customers**" : "school_admin_id"
    "**tapestry_trials**" ||..|| "**tapestry_schools**" : ""
    "**tapestry_trials**" }o..|| "**nexus_customers**" : ""
    "**tapestry_trials**" }o..o| "**nexus_purchases**" : ""
    "**tapestry_promised**" }o..|| "**nexus_invoices**" : ""
    "**tapestry_promised**" }o..|| "**tapestry_schools**" : ""
    "**nexus_alternate_contacts**" }o..|| "**nexus_customers**" : "alt_id, non-EU"
    "**tapestry_findus**" }o..o| "**nexus_customers**" : ""
    "**cms_custom_database_21**" ||..o| "**tapestry_schools**" : "trial request"
    "**tapestry_api_log**" }o..o| "**tapestry_schools**" : "LIKE match"
    "**foundation_la**" ||..o{ "**foundation_group_upgrade_history**" : "current"
    "**foundation_group_passwords**" ||..o{ "**foundation_group_upgrade_history**" : "legacy"
    "**core_members**" ||..o{ "**foundation_group_upgrade_history**" : ""
    "**foundation_la**" }o..|| "**core_clubs**" : ""
    "**foundation_la**" ||..o{ "**foundation_la_extension_history**" : ""
    "**foundation_group_passwords**" }o..|| "**core_groups**" : ""
