---
    title: COMMERCIAL SPINE - FULL TABLE DESCRIPTION
---
erDiagram
    "**core_members**" {
        bigint member_id PK
        string name "forum display name"
    }
    "**nexus_customers**" {
        bigint member_id PK, FK "FK → core_members.member_id. A Nexus customer is a forum member; this table is the commerce extension of it."
        varchar cm_first_name "Billing first name. Distinct from the forum display name."
        varchar cm_last_name "Billing last name."
        varchar cm_phone "Phone number. Shown next to the setting in the ACP settings list."
        text cm_profiles "JSON. Per-gateway stored customer/profile IDs (e.g. a gateway vault token)."
        varchar field_1 "Generated column for custom customer field #1. The field definition — its name, type and this column name — lives in nexus_customer_fields; one such column is added per field."
    }
    "**nexus_invoices**" {
        int i_id PK "Primary key. The invoice number customers and Tapestry both quote."
        char i_status "paid · pend (unpaid) · expd (expired unpaid) · canc (cancelled)."
        varchar i_title "Invoice title."
        bigint i_member FK "FK → nexus_customers.member_id. 0 for a guest checkout — see i_guest_data."
        text i_items "JSON line items (newer rows) or a PHP-serialised array (legacy rows). The Promise code has to handle both."
        decimal i_total "Gross total including tax."
        int i_date "Unix timestamp raised."
        varchar i_return_uri "Where to send the customer after payment."
        int i_paid "Unix timestamp paid. Payment here is what triggers Tapestry provisioning."
        text i_status_extra "JSON detail behind the status (e.g. why it was cancelled)."
        smallint i_discount "Discount amount applied."
        text i_renewal_ids "JSON list of nexus_purchases.ps_id this invoice renews."
        varchar i_po "Customer purchase-order number. Used heavily by schools paying on invoice."
        text i_notes "Free-text notes shown on the invoice."
        text i_shipaddress "JSON snapshot of the shipping address at the time."
        text i_billaddress "JSON snapshot of the billing address at the time."
        char i_currency "ISO currency code."
        text i_guest_data "JSON checkout details for a guest invoice. Guest checkout cannot view the printed invoice — see applications/tapestry/hooks/printInvoicCredit.php."
        char i_billcountry "ISO country code of the billing address, denormalised for tax reporting."
    }
    "**nexus_transactions**" {
        int t_id PK "Primary key."
        bigint t_member FK "FK → nexus_customers.member_id."
        int t_invoice FK "FK → nexus_invoices.i_id."
        int t_method FK "FK → nexus_paymethods.m_id. NULL where the payment came from account credit."
        char t_status "okay paid · pend not yet submitted · wait awaiting the customer (e.g. cheque in the post) · hold held for approval · revw flagged for staff review · fail refused · rfnd refunded · prfd part-refunded · gwpd gateway processing · dspd disputed/chargeback."
        decimal t_amount "Amount taken."
        int t_date "Unix timestamp."
        text t_extra "JSON gateway response payload."
        text t_fraud FK "FK → nexus_fraud_rules.f_id that matched, if any."
        varchar t_gw_id "The gateway’s own transaction reference. For GlobalPay this is the Realex order/pasref."
        varchar t_ip "Payer IP address."
        int t_fraud_blocked "Set when a fraud rule blocked the transaction."
        char t_currency "ISO currency code."
        decimal t_partial_refund "Amount refunded so far where t_status is prfd."
        int t_auth "Unix timestamp the authorisation expires (auth-then-capture flows)."
        bigint t_billing_agreement FK "FK → nexus_billing_agreements.ba_id where this was an automatic collection."
        decimal t_credit "Portion of the payment taken from the customer’s account credit rather than the gateway."
    }
    "**nexus_paymethods**" {
        int m_id PK "Primary key. The method name is a language key derived from this ID, not a column."
        varchar m_gateway "Gateway class — Stripe, PayPal, Manual, GlobalPay, …. GlobalPay (Realex) is the custom one; BACS/purchase-order payments run through a Manual method."
        text m_settings "JSON gateway credentials and options."
        tinyint m_active "Available at checkout."
        int m_position "Sort order."
        text m_countries "Comma-separated ISO country codes this method is offered in, or *."
        varchar m_validationfile "Path to a gateway domain-verification file (e.g. Apple Pay)."
    }
    "**nexus_purchases**" {
        int ps_id PK "Primary key. The Tapestry link: tapestry_schools.school_pkg_id = ps_id. One live purchase = one Tapestry setting."
        bigint ps_member FK "FK → nexus_customers.member_id — who owns the subscription."
        varchar ps_name "Display name, denormalised at purchase time."
        tinyint ps_active "1 = live. Read by the Tapestry provisioning hooks: this is what decides whether the account is switched on."
        tinyint ps_cancelled "1 = cancelled by customer or staff (as opposed to simply lapsed)."
        int ps_start "Unix timestamp the subscription began."
        int ps_expire "Unix timestamp of the next renewal date. 0 = never expires. Surfaced in the ACP settings list as “Expires”."
        int ps_renewals "JSON renewal term (amount, currency, interval)."
        decimal ps_renewal_price "Renewal amount."
        char ps_renewal_unit "Renewal interval unit (d/m/y)."
        varchar ps_app "Owning application — nexus for store purchases."
        varchar ps_type "Purchase subclass — package, subscription, …"
        int ps_item_id FK "FK → nexus_packages.p_id (for ps_app=nexus, ps_type=package). Joined to tapestry_packages.id to read the child allowance."
        varchar ps_item_uri "Front-end URL for the purchased item."
        varchar ps_admin_uri "ACP URL for the purchased item. Written by the provisioning task so staff can jump into Tapestry."
        mediumtext ps_custom_fields "JSON, keyed by nexus_package_fields.cf_id. Key 1 is the setting name, kept in step with Tapestry."
        text ps_extra "JSON extension-specific payload."
        int ps_parent FK "FK → nexus_purchases.ps_id for an associated child purchase."
        int ps_invoice_pending FK "FK → nexus_invoices.i_id — the unpaid renewal invoice, if one is out."
        tinyint ps_invoice_warning_sent "Unix timestamp the “about to expire” warning went out."
        bigint ps_pay_to "Commission recipient (marketplace feature)."
        int ps_commission "Commission percentage."
        int ps_original_invoice FK "FK → nexus_invoices.i_id — the invoice that created the purchase."
        int ps_tax FK "FK → nexus_tax.t_id applied at renewal."
        tinyint ps_can_reactivate "Whether a lapsed purchase may be reactivated by paying."
        text ps_grouped_renewals "Renew together with sibling purchases on one invoice."
        char ps_renewal_currency "ISO currency of the renewal amount."
        tinyint ps_show "Show in the customer’s client area. 0 hides internal/system purchases."
        int ps_grace_period "Seconds past ps_expire that this purchase stays active, overriding p_grace_period."
        bigint ps_billing_agreement FK "FK → nexus_billing_agreements.ba_id for an automatic recurring mandate."
        decimal ps_fee "Per-renewal fee added on top."
    }
    "**nexus_packages**" {
        int p_id PK "Primary key. This is the ID that tapestry_packages.id mirrors."
        varchar p_name "Language-key stem; the human title lives in core_sys_lang_words."
        varchar p_seo_name "URL slug."
        int p_group FK "FK → nexus_package_groups.pg_id — the store category."
        int p_stock "Stock level; -1 = unlimited."
        tinyint p_reg "Offer this package during registration."
        tinyint p_store "Show in the public store. Packages sold only by staff or by API are hidden here."
        text p_member_groups "Comma-separated core_groups.g_id allowed to buy, or *."
        tinyint p_allow_upgrading "Comma-separated package IDs this may be upgraded to, or *. Drives the Tapestry size-change journey."
        tinyint p_upgrade_charge "How the upgrade difference is charged (pro-rata vs full)."
        tinyint p_allow_downgrading "As above, for downgrades."
        tinyint p_downgrade_refund "How a downgrade is refunded (none / credit / refund)."
        text p_base_price "JSON map of currency → amount. See also nexus_package_base_prices."
        int p_tax FK "FK → nexus_tax.t_id."
        int p_renewal_days "Renewal term length, in the unit given by the renewal options."
        mediumint p_primary_group "Primary forum group granted while the purchase is active."
        text p_secondary_group "Secondary forum groups granted while active."
        tinyint p_return_primary "Primary group to restore when the purchase ends."
        tinyint p_return_secondary "Secondary groups to strip when the purchase ends."
        int p_position "Sort order within the group."
        text p_associable "Packages that may be attached as children of this one."
        tinyint p_force_assoc "Require an association at checkout."
        text p_assoc_error "Language key for the error shown when the association is missing."
        text p_discounts "JSON bulk/loyalty discount rules."
        mediumtext p_page FK "FK → a CMS page used as the product description."
        tinyint p_support "Purchasing this grants support access."
        int p_support_department FK "FK → nexus_support_departments.dpt_id for tickets raised against it."
        int p_support_severity FK "FK → nexus_support_severities.sev_id."
        tinyint p_featured "Featured in the store."
        tinyint p_upsell "JSON of packages to cross-sell."
        text p_notify "Staff emails notified on purchase."
        varchar p_type "Package subclass — product, subscription, ads, …. Tapestry packages are product."
        mediumint p_custom "JSON of package custom-field values/config."
        tinyint p_reviewable "Allow customer reviews."
        tinyint p_review_moderate "Hold reviews for approval."
        varchar p_image "Store image."
        text p_methods "Comma-separated nexus_paymethods.m_id accepted, or blank for all."
        text p_renew_options "JSON of the renewal terms offered at checkout."
        tinyint p_group_renewals "Combine renewals of this package onto one invoice."
        tinyint p_rebuild_thumb "Internal flag for the thumbnail rebuild task."
        int p_renewal_days_advance "How many days before expiry the renewal invoice is generated."
        int p_date_added "Unix timestamp."
        int p_reviews "Denormalised count of approved reviews."
        float p_rating "Denormalised average rating."
        int p_unapproved_reviews "Denormalised count awaiting moderation."
        int p_hidden_reviews "Denormalised count of hidden reviews."
        int p_grace_period "Seconds a lapsed purchase stays active past expiry before it is switched off. This is the stock mechanism the Promised Payment process works alongside."
        tinyint p_meta_data "JSON SEO meta."
        mediumtext p_email_purchase "Custom email body sent on purchase."
        mediumtext p_email_expire_soon "Custom email body sent before expiry."
        mediumtext p_email_expire "Custom email body sent on expiry."
        varchar p_email_purchase_type "Whether that email replaces or appends to the default."
        varchar p_email_expire_soon_type "Replace or append."
        varchar p_email_expire_type "Replace or append."
        int p_date_updated "Unix timestamp."
        varchar p_initial_term "A different term (and price) for the first period."
    }
    "**nexus_package_groups**" {
        int pg_id PK "Primary key."
        varchar pg_name "Language-key stem."
        varchar pg_seo_name "URL slug."
        int pg_position "Sort order."
        int pg_parent FK "FK → nexus_package_groups.pg_id; -1 for a root group."
        text pg_image "Category image."
        text pg_filters "Comma-separated nexus_package_filters.pf_id offered in this category."
        text pg_price_filters "JSON price bands offered as a filter in this category."
    }
    "**tapestry_packages**" {
        bigint id PK, FK "FK → nexus_packages.p_id. A row existing here is what makes a Nexus package 'a Tapestry package' — Schools::isTapestryPackage() is literally a lookup on this column. Declared AUTO_INCREMENT, but always written explicitly as the Nexus package ID."
        int children "The child allowance the package grants. Schools::packages() keys the whole price ladder by this."
    }
    "**tapestry_schools**" {
        int school_id "Shared with Tapestry — the same integer identifies the setting on both sides. Auto-increment, but the provisioning task will reassign it to MAX(school_id)+1 if Tapestry reports the ID already exists."
        int school_added "Unix timestamp the setting was queued."
        tinyint school_enabled "1 = live. Set to 0 on cancel or expiry, back to 1 on reactivation or trial extension."
        varchar school_email "Account owner's email at creation time."
        varchar school_name "Setting name. Tapestry owns this — a rename is pushed back here by POST /tapestry/settingdetails/{id}."
        varchar school_furl_slug "URL slug. Generated locally, then overwritten with whatever Tapestry returns from addSchool."
        varchar school_address1 "Address line 1. Dormant — addToQueue() writes '' and nothing in this codebase updates it. The value is still forwarded to Tapestry's addSchool call, so new settings are provisioned with a blank address. Older rows may hold real data from a previous code path."
        varchar school_address2 "Address line 2. Same as above."
        varchar school_city "City. Same as above."
        varchar school_county "County. Same as above."
        varchar school_postcode "Postcode. Same as above."
        text school_geoloc "Geolocation. Dormant — written '' on creation, never read or updated."
        varchar school_fsf_key "Intended to hold the LA scheme key used at sign-up. Dormant — both callers of addToQueue() pass '', and nothing reads it."
        int school_admin_id FK "FK → core_members.member_id / nexus_customers.member_id — the account owner. Joined in almost every settings query."
        int school_ofsted_id "Ofsted URN. Dormant — written as 0 on creation, never updated. The URN that is actually used lives on the trial request (cms_custom_database_21.field_159)."
        int school_pkg_id FK "FK → nexus_purchases.ps_id. The subscription paying for this setting. Declared as a secondary ID field, so Schools::load( $id, 'school_pkg_id' ) loads a setting straight from a purchase."
        int school_max_children "Child allowance, denormalised from tapestry_packages.children at the point of purchase or change."
        int school_setup_queued "Provisioning queue counter. > 0 means the create task should pick it up; it doubles as the retry count and gives up after 3."
        int school_setting_up "Unix timestamp lock, so two runs of the create task cannot provision the same setting. Cleared automatically after 10 minutes."
        tinyint school_trial "1 = this is a trial account."
        int school_trial_expires "Unix timestamp the trial ends. Kept in step with nexus_purchases.ps_expire."
        int school_version "Tapestry platform version. Hard-coded to 2 for new settings; never read here."
        int school_status_changed_at "Unix timestamp of the last cancel, expire or reactivate. Sent to Tapestry so it can discard out-of-order status pushes. (The one column with a real schema definition.)"
        int school_details_updated_at "Unix timestamp of the last details push from Tapestry. An inbound push carrying an older timestamp is discarded — this is the conflict resolution for a field both systems can write."
        tinyint school_non_eu_processing_consent "Whether the setting has consented to its data being processed outside the EU. Collected in Tapestry, acted on here. Changing it resets every related ticket to r_non_eu_status = 3 (needs recheck)."
    }
    "**tapestry_trials**" {
        int trial_id "Primary key."
        int trial_school_id FK "FK → tapestry_schools.school_id. Declared as a secondary ID field: Trials::load( $schoolId, 'trial_school_id' ) is how the purchase hooks find the trial."
        int trial_customer_id FK "FK → nexus_customers.member_id."
        int trial_purchase_id FK "FK → nexus_purchases.ps_id. 0 where no purchase was created."
        int trial_created_timestamp "When the trial was set up."
        int trial_expires "When it runs out. Kept in step with ps_expire and school_trial_expires — extend() writes all three."
        int trial_converted_timestamp "When it became a paid account. 0 = never did."
        tinyint trial_upgraded "1 = converted to a paid package."
        tinyint trial_cancelled "1 = cancelled. Reset to 0 by extend() and by conversion, so a cancelled trial can be revived."
        text trial_data "JSON snapshot of the address supplied on the trial form."
    }
    "**tapestry_promised**" {
        int promise_id PK "Primary key."
        int promise_invoice_id FK "FK → nexus_invoices.i_id — the unpaid invoice being held open."
        varchar promise_invoice_total "Invoice total as a display string, denormalised so the ACP list does not have to load the invoice."
        int promise_school_id FK "FK → tapestry_schools.school_id."
        int promise_date_added "Unix timestamp the promise was recorded."
        int promise_date_expire "Unix timestamp the promise runs out. Past this, the account is no longer held open."
        int promise_actioned "0 = live, 1 = dealt with. The invoice_promise index is on (promise_invoice_id, promise_actioned) because the hot query is 'is there a live promise for this invoice?'."
        text promise_purchase_expiration "JSON snapshot of the original ps_expire of each affected purchase, so the real expiry date can be restored when the promise is cancelled or expires."
        int promise_reminder_last_emailed "Unix timestamp the last chase email went out."
        int promise_expired_notice_sent "Unix timestamp the 'promise expired' notice went out. 0 = not sent."
    }
    "**nexus_support_requests**" {
        int r_id PK "Primary key — the ticket number."
        varchar r_title "Ticket subject."
        bigint r_member FK "FK → nexus_customers.member_id. 0 when the ticket arrived by email from an unknown address."
        int r_department FK "FK → nexus_support_departments.dpt_id."
        int r_purchase FK "FK → nexus_purchases.ps_id the ticket is raised against."
        int r_status FK "FK → nexus_support_statuses.status_id."
        int r_severity FK "FK → nexus_support_severities.sev_id."
        tinyint r_severity_lock "Staff have pinned the severity; the customer cannot change it."
        int r_started "Unix timestamp opened."
        int r_last_reply "Unix timestamp of the most recent reply of any kind."
        bigint r_last_reply_by FK "FK → core_members.member_id."
        int r_last_new_reply "Unix timestamp of the most recent customer reply."
        int r_last_staff_reply "Unix timestamp of the most recent staff reply."
        bigint r_staff FK "FK → core_members.member_id — the assigned agent."
        tinyint r_staff_lock "Ticket is locked to that agent."
        int r_replies "Denormalised reply count."
        text r_notify "JSON list of members watching the ticket."
        varchar r_email "Originating email address for an email-in ticket."
        char r_email_key "Token embedded in outgoing mail so replies thread back to this ticket."
        tinyint r_ar_notify "Auto-responder bookkeeping."
        mediumtext r_cfields "JSON custom field values, keyed by nexus_support_fields.sf_id."
        int r_ppi_invoice FK "FK → nexus_invoices.i_id for pay-per-incident support."
        int r_non_eu_status "CUSTOM — 0 not checked · 1 visible to non-EU staff · 2 not visible · 3 needs recheck. See §5."
        int r_non_eu_status_changed_at "CUSTOM — when the computed status last changed."
        int r_non_eu_override "CUSTOM — 0 none · 1 force visible · 2 force hidden. Beats r_non_eu_status."
        int r_non_eu_overridden_by FK "CUSTOM — FK → core_members.member_id."
        int r_non_eu_overridden_at "CUSTOM — when the override was set."
    }
    "**tapestry_support_request_schools**" {
        int request_id PK, FK "FK → nexus_support_requests.r_id."
        int school_id PK, FK "FK → tapestry_schools.school_id."
    }
    "**foundation_la**" {
        int la_id PK "Primary key. This is the value written to foundation_group_upgrade_history.rkeyid."
        varchar la_password "The scheme key a practitioner types to claim membership. Declared as a secondary ID field, so keys are looked up by this value directly."
        int la_used "Redemption counter, carried over from foundation_group_passwords.pused when a scheme was migrated. Dormant — the ACP column labelled 'used' is a live COUNT(*) over core_clubs_memberships, not this value."
        varchar la_title "Scheme name — normally the Local Authority."
        int la_club_id FK "FK → core_clubs.id. Redeeming the key joins the member to this club, which is what grants the private forums."
        smallint la_enabled "0 disables the key without deleting it or its history. Drives the active/inactive filter in the ACP. Set to 0 automatically for any migrated scheme whose password contained schemeexpired."
    }
    "**foundation_group_upgrade_history**" {
        int rid PK "Primary key."
        int rkeyid "The scheme the member redeemed. Current writers set this to foundation_la.la_id; the ACP settings list still LEFT JOINs it to foundation_group_passwords.pid, which is the legacy path (see the drift note below)."
        int ruserid FK "FK → core_members.member_id."
        int ruseddate "Unix timestamp redeemed."
        int rexpiredate "Unix timestamp the membership lapses. rexpiredate > now is the test for 'this member currently has LA membership' — used by the inactive-member deletion task to avoid deleting paid members."
    }
    "**core_clubs**" {
        int id PK
        string name "forum club, grants private forums"
    }
    "**core_members**"            ||..|| "**nexus_customers**"        : "is a"
    "**nexus_customers**"         ||..o{ "**nexus_invoices**"          : "raises"
    "**nexus_invoices**"          ||..o{ "**nexus_transactions**"      : "settled by"
    "**nexus_transactions**"      }o..|| "**nexus_paymethods**"        : "via"
    "**nexus_customers**"         ||..o{ "**nexus_purchases**"         : "owns"
    "**nexus_invoices**"          ||..o{ "**nexus_purchases**"         : "ps_original_invoice"
    "**nexus_purchases**"         }o..|| "**nexus_packages**"          : "ps_item_id"
    "**nexus_packages**"          }o..|| "**nexus_package_groups**"    : "p_group"
    "**nexus_packages**"          ||..o| "**tapestry_packages**"       : "p_id = id"
    "**nexus_purchases**"         ||..o| "**tapestry_schools**"        : "ps_id = school_pkg_id"
    "**nexus_customers**"         ||..o{ "**tapestry_schools**"        : "school_admin_id"
    "**tapestry_schools**"        ||..o| "**tapestry_trials**"         : "school_id"
    "**tapestry_schools**"        ||..o{ "**tapestry_promised**"       : "school_id"
    "**tapestry_schools**"        ||..o{ "**tapestry_support_request_schools**" : "school_id"
    "**nexus_support_requests**"  ||..o{ "**tapestry_support_request_schools**" : "r_id"
    "**nexus_customers**"         ||..o{ "**nexus_support_requests**"  : "r_member"
    "**nexus_purchases**"         ||..o{ "**nexus_support_requests**"  : "r_purchase"
    "**foundation_la**"           ||..o{ "**foundation_group_upgrade_history**" : "rkeyid"
    "**core_members**"            ||..o{ "**foundation_group_upgrade_history**" : "ruserid"
    "**foundation_la**"           }o..|| "**core_clubs**"              : "la_club_id"
